#!/usr/bin/env  zsh

if [ -x `which gtags` ]
   gtags
elif 
   git ls-files > cscope.files 
   cscope -b -R
else
  CTAGS=`which ctags`
  $CTAGS --tag-relative --recurse --sort=yes --append=no  -f .git/tags 
fi
 
