#!/bin/zsh

set -eEu

find "$(wslpath "$(wslvar USERPROFILE)")/AppData/Roaming/Code/User/" \
  -maxdepth 1 -type f \
  -exec cp -v {} ~/.config/Code/User/ \;


DOTDIR=$(dirname $(dirname $(readlink -f =wsl-vscode-pull)))
powershell.exe "code --list-extensions" 2>/dev/null > ${DOTDIR}/VSCodeExtensions
