#!/usr/bin/env zsh
#
autoload -Uz fzf-cmd


fdr() {
    local declare dirs=()
    local declare get_parent_dirs() {
        if [[ -d "${1}" ]]; then dirs+=("$1"); else return; fi
        if [[ "${1}" == '/' ]]; then
            for _dir in "${dirs[@]}"; do 
                echo $_dir;
            done
        else
            get_parent_dirs $(dirname "$1")
        fi
    }
    local DIR=$(get_parent_dirs $(realpath "${1:-$PWD}") | $(fzf-cmd))
    cd "$DIR"
}

fdr $@
