#!/bin/zsh

fzf_aws_ec2(){
    FZF_OPTS=${(z)@}
    {
        CACHE_PATH=/tmp/_cache_aws_ec2_instances.json
        if [[ ! -f $CACHE_PATH ]]; then
            (( $+commands[aws] )) && aws ec2 describe-instances > $CACHE_PATH
        elif [[ $(date +'%j') != $(stat -f '%m' -t '%j' $CACHE_PATH  | date +%j) ]]; then
            # NOTE: Daily Cache
            (( $+commands[aws] )) && aws ec2 describe-instances > $CACHE_PATH
        fi
        cat $CACHE_PATH
    } | jq -r '
            .Reservations[].Instances[] 
            | { 
                Name: ([.Tags[]?] | from_entries | .Name),
                Address: (.PublicIpAddress),
              } 
            | to_entries | [ .[]? | "\(.key):\"\(.value[:30])\""]
            | join(",")
        ' | column -t -s,\
        | fzf $FZF_OPTS \
        | sed 's/"  */",/' \
        | jq -Rr '
            rtrimstr("\n") | split(",") | [ 
                .[]? | split(":") | { 
                    key: .[0], 
                    value: .[1] | ltrimstr("\"") | rtrimstr("\"") 
                }] 
            | from_entries
            | "ssh \(.Address)"
        '
}

fzf_aws_ec2 $@
