#!/usr/bin/env zsh
#
autoload -Uz fzf-cmd

fzf-history-widget() {
  local selected num
  selected=( $(fc -l 1 | $(fzf-cmd) +s --tac +m -n2..,.. --tiebreak=index --toggle-sort=ctrl-r ${=FZF_CTRL_R_OPTS} -q "${LBUFFER//$/\\$}") )
  if [ -n "$selected" ]; then
    num=$selected[1]
    if [ -n "$num" ]; then
      zle vi-fetch-history -n $num
    fi
  fi
  zle redisplay
}
 
