#!/usr/bin/env zsh

autoload -Uz ghq-finder-by-fzf

ghq-finder-by-fzf() {
    local dir repository session current_session
    FZF=fzf
    dir=$(ghq root)/$(ghq list | $FZF --reverse +m --prompt='Project >')

    if [[ $dir != "$(ghq root)/" ]]; then
        if [[ ! -z ${TMUX} ]]; then
            repository=${dir##*/}
            session=${repository//./-}
            current_session=$(tmux list-sessions | grep 'attached' | cut -d":" -f1)

            if [[ $current_session =~ ^[0-9]+$ ]]; then
                tmux send-key -t $current_session "cd $dir" Enter
                tmux rename-session $session
            else
                tmux list-sessions | cut -d":" -f1 | grep $session$ > /dev/null
                if [[ $? != 0 ]]; then
                    tmux new-session -d -c $dir -s $session
                fi
                tmux switch-client -t $session
            fi
        else
            cd $dir
        fi
  fi
}

ghq-finder-by-fzf $@ 
