#!/usr/bin/env zsh

autoload -Uz ghq-finder-by-fzf

_GHQ_ROOT=$(ghq root)
_AWK_GROUP_BY_MIN='
{
    if(min[$1] == "") min[$1]="inf"
    if(min[$1]>$2) min[$1]=$2
}
END{for(key in min) print key, min[key]}
'

ghq-list-historical-ordered() {
    join -a 1 -e 1000 -o 0,2.2 \
        <(ghq list | sort) \
        <(cat $DIRSTACKFILE | grep "$_GHQ_ROOT" | sed "s:$_GHQ_ROOT/::" | cut -d/ -f1,2,3 | nl | awk '{print $2,$1}' | awk "$_AWK_GROUP_BY_MIN" | sort) \
    | sort -k2n \
    | awk '{print $1}'
}

ghq-finder-by-fzf() {
    local dir repository workspace session current_session current_window
    FZF=fzf

    dir="$_GHQ_ROOT/$(ghq-list-historical-ordered | $FZF --reverse +s +m --prompt='Project >')"

    if [[ $dir != "$(ghq root)/" ]]; then
        if [[ ! -z ${TMUX} ]]; then
            repository=${dir##*/}
            session=${repository%%+*}
            workspace=$([[ ${repository#*+} != $session ]] && echo ${repository#*+} || echo "trunk")
            current_session=$(tmux list-sessions | grep 'attached' | cut -d":" -f1)
            current_window=$(tmux list-windows | grep '(active)' | cut -d" " -f2)

            # Switch session
            if [[ $current_session =~ ^[0-9]+$ ]]; then
                tmux send-key -t "$current_session" "cd $dir" Enter
                tmux rename-session $session
            else
                if ! { tmux list-sessions | cut -d":" -f1 | grep "$session$" > /dev/null; }; then
                    tmux new-session -d -c $dir -s $session -n $workspace
                fi
                tmux switch-client -t $session
            fi

            # Workspace management
            if ! { tmux list-windows | cut -d" " -f2 | grep "$workspace" > /dev/null; }; then
                tmux new-window -d -c $dir -n $workspace
            fi
            tmux select-window -t $workspace

        elif [[ ! -z ${VSCODE_IPC_HOOK_CLI} ]]; then
            code $dir
        else
        fi
  fi
}

ghq-finder-by-fzf $@
