#!/bin/zsh

tmux-sync_cmd() {
    while read cmd; do 
        tmux split-window -h "echo $cmd; $cmd;"
        tmux set-option remain-on-exit on
        tmux select-layout main-horizontal
    done
}

tmux-sync_cmd $@
