#!/bin/zsh

tmux-sync_cmd() {
    while read cmd; do 
        tmux split-window -h "echo $cmd; $cmd;"
        tmux select-layout main-horizontal
    done
    tmux set-window-option remain-on-exit on
}

tmux-sync_cmd $@
